version: "3.5"

services:
        mongo:
                container_name: 'mongo'
                image: mongo
                networks:
                        - web
        parse-server:
                container_name: 'parse-server'
                image: parseplatform/parse-server
                environment:
                        - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/yourdatabasename
                        - PARSE_SERVER_APPLICATION_ID=APP_ID
                        - PARSE_SERVER_MASTER_KEY=MASTER_KEY
                expose:
                        - "1337"
                depends_on:
                        - mongo
                networks:
                      - web
                labels:
                      - "traefik.docker.network=web"
                      - "traefik.enable=true"
                      - "traefik.basic.frontend.rule=Host:parse.example.com"
                      - "traefik.basic.port=1337"
                      - "traefik.basic.protocol=http"

        parse-dashboard:
                container_name: 'parse-dashboard'
                image: parseplatform/parse-dashboard
                environment:
                        - PORT=4040
                        - MOUNT_PATH=/
                        - PARSE_DASHBOARD_TRUST_PROXY=1
                        - PARSE_DASHBOARD_SERVER_URL=https://parse.example.com/parse
                        - PARSE_DASHBOARD_MASTER_KEY=MASTER_KEY
                        - PARSE_DASHBOARD_APP_ID=APP_ID
                        - PARSE_DASHBOARD_APP_NAME=APPNAME
                        - PARSE_DASHBOARD_USER_ID=CHANGE_THIS
                        - PARSE_DASHBOARD_USER_PASSWORD=CHANGE_THIS
                expose:
                        - "4040"
                depends_on:
                        - parse-server 
                networks:
                      - web
                labels:
                      - "traefik.docker.network=web"
                      - "traefik.enable=true"
                      - "traefik.basic.frontend.rule=Host:dashboard.example.com"
                      - "traefik.basic.port=4040"
                      - "traefik.basic.protocol=http"

networks:
        web:
                external: true
